.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo2 - Debug ]----------"
	@cd "Ejemplo2" && "$(MAKE)" -f  "Ejemplo2.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo2 - Debug ]----------"
	@cd "Ejemplo2" && "$(MAKE)" -f  "Ejemplo2.mk" clean
