.PHONY: clean All

All:
	@echo "----------Building project:[ Ejercicio2 - Debug ]----------"
	@cd "Ejercicio2" && "$(MAKE)" -f  "Ejercicio2.mk"
clean:
	@echo "----------Cleaning project:[ Ejercicio2 - Debug ]----------"
	@cd "Ejercicio2" && "$(MAKE)" -f  "Ejercicio2.mk" clean
