.PHONY: clean All

All:
	@echo "----------Building project:[ Ejercicio1 - Debug ]----------"
	@cd "Ejercicio1" && "$(MAKE)" -f  "Ejercicio1.mk"
clean:
	@echo "----------Cleaning project:[ Ejercicio1 - Debug ]----------"
	@cd "Ejercicio1" && "$(MAKE)" -f  "Ejercicio1.mk" clean
