.PHONY: clean All

All:
	@echo "----------Building project:[ Ejercicio08Def - Debug ]----------"
	@cd "Ejercicio08Def" && "$(MAKE)" -f  "Ejercicio08Def.mk"
clean:
	@echo "----------Cleaning project:[ Ejercicio08Def - Debug ]----------"
	@cd "Ejercicio08Def" && "$(MAKE)" -f  "Ejercicio08Def.mk" clean
