.PHONY: clean All

All:
	@echo "----------Building project:[ Ejercicio3a - Debug ]----------"
	@cd "Ejercicio3a" && "$(MAKE)" -f  "Ejercicio3a.mk"
clean:
	@echo "----------Cleaning project:[ Ejercicio3a - Debug ]----------"
	@cd "Ejercicio3a" && "$(MAKE)" -f  "Ejercicio3a.mk" clean
