.PHONY: clean All

All:
	@echo "----------Building project:[ Ejercicio05 - Debug ]----------"
	@cd "Ejercicio05" && "$(MAKE)" -f  "Ejercicio05.mk"
clean:
	@echo "----------Cleaning project:[ Ejercicio05 - Debug ]----------"
	@cd "Ejercicio05" && "$(MAKE)" -f  "Ejercicio05.mk" clean
